name: Tests

on: [push, pull_request]

jobs:
  build-release:
    name: Build Ubuntu Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install crosstools
        if: runner.os == 'Linux'
        run: |
          git clone https://github.com/crosstool-ng/crosstool-ng
          cd crosstool-ng
          ./bootstrap
          ./configure --prefix=$HOME/.local
          make
          make install
          export PATH=$HOME/.local/bin:$PATH
          ct-ng help

#      - name: Build on Linux
#        if: runner.os == 'Linux'
#        run: |
#          cargo install cargo-zigbuild
#          cargo --verbose zigbuild --bin kaspad --bin simpa --bin rothschild --release --target x86_64-unknown-linux-gnu.2.27 # Use an older glibc version
