name: Tests

on: [push, pull_request]

jobs:
  build-release:
    name: Build Ubuntu Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Build Outputs
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
        
      - name: Cache Crosstool-NG Tools
        uses: actions/cache@v4
        with:
          path: |
            ~/ctng
          key: ${{ runner.os }}-crosstool-ng-${{ hashFiles('**/.config') }}
          restore-keys: |
            ${{ runner.os }}-crosstool-ng-

      
      - name: Install Crosstool-NG and build toolchain
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool libtool-bin unzip help2man python3.10-dev gperf bison flex texinfo gawk libncurses5-dev
          git clone https://github.com/crosstool-ng/crosstool-ng
          cd crosstool-ng
          ./bootstrap
          ./configure --prefix=$HOME/ctng
          make
          make install
          export PATH=$HOME/ctng/bin:$PATH
    